### ISSUE TITLE
logging configuration file format to yaml

### ISSUE THREAD

**Issue by Nanjangpan** [Nanjangpan/NewsDashboard#3]
@tldms0327 
logging.conf파일 config.yml 통합 코드 예시 입니다.

설정 값들은 모두 config.yml로 통합하는 것이 좋을 것 같습니다.

자세한 내용은 첨부 폴더 참조해주세요.

예) 

- config.yml
```
model_config:
    als: ...
logging_config:
    ...
    formatters: ...
    handlers: ...
    loggers:
        root: ...
        simpleExample: ...
other_config: ...
```

- _example_.py
```
import yaml
configs = yaml.load(open("./config.yml").read(), Loader=yaml.Loader)
model_config = configs["model_config"]
logging_config = configs["logging_config"]

# insert "logging_config" values into logging config
logging.config.dictConfig(logging_config)
```

FOLDER: [config_yaml.7z](/uploads/563caa8e569ce7b19432517ded38346b/config_yaml.7z)
